# -*- coding: utf-8 -*-
"""SeabornPython.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sdepRG7ZhuGk_2ZtEVWDXukWRWlR0tmB

Seaborn library in Python :
  Important library for data visulization in Python
"""

import seaborn as sb
import matplotlib.pyplot as mpt
import pandas as pd
import numpy as np

"""Seaborn has some built in data sets"""

tips = sb.load_dataset("tips") # loading the tips dataset from seaborn

tips.head()

# setting the theme for seaborn
sb.set_theme()

# visulazing the data using Seaborn library
sb.relplot(data = tips, x = "total_bill", y = "tip", col = "time", hue = "smoker", style = "smoker", size = "size")

# another dataset named iris
iris = sb.load_dataset("iris")
iris.head()

"""For this, we are going to create Scatter plot os Seaborn"""

# visualizing the iris dataset

sb.scatterplot(x = "sepal_length", y = "petal_length", hue = "species", data = iris)

"""Loading the new dataset named Titanic"""

titanic = sb.load_dataset("titanic")
titanic.head()

"""Loading the

Count Plot
"""

sb.countplot(x = "class", data = titanic)

sb.countplot(x = "survived", data = titanic)

"""Bar Chart in Seaborn"""

sb.barplot(x = "sex", y = "survived", hue = "class", data = titanic)

"""New dataset named calfornia housing dataset, we are going to load, that we are going to import from sklearn library"""

from sklearn.datasets import fetch_california_housing

cf = fetch_california_housing()

house = pd.DataFrame(cf.data, columns = cf.feature_names)
house["PRICE"] = cf.target

house.head()

house.columns

"""Distribution plot using Seaborn"""

sb.displot(house["PRICE"])

"""Co relation matrix
- Positive corelation -> one value increases then another value also increases
- Negative corelation -> one value increases then another value decreases

for this, we'll create Heat Map
"""

correlation = house.corr()

# construting the Heat Map
mpt.figure(figsize=(10,10))
sb.heatmap(correlation, cbar = True, square = True, fmt = ".1f", annot = True, annot_kws = {"size" : 8}, cmap= 'Blues')